/**
 * Requirement Intelligence Engine — Agent Types
 *
 * Shared types consumed by the Requirement Agent, Validation Agent,
 * and the API layer that connects them to the frontend.
 */

import type { RequirementFieldKey } from './requirement';
import type { Message } from './conversation';

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

export type ValidationSeverity = 'missing' | 'low-confidence' | 'ambiguous' | 'conflicting';

export interface ValidationIssue {
  field: RequirementFieldKey;
  severity: ValidationSeverity;
  message: string;
  suggestedQuestion: string;
}

// ---------------------------------------------------------------------------
// Agent response
// ---------------------------------------------------------------------------

/** Structured response returned by the Requirement Agent for every user message. */
export interface AgentResponse {
  /** The conversational reply to show the user. */
  message: string;
  /** Newly extracted or updated requirement fields (sparse — only changed keys). */
  extractedRequirements: Record<string, unknown>;
  /** Intelligent follow-up questions the agent wants to ask. */
  followUpQuestions: string[];
  /** Validation issues detected after merging. */
  validationIssues: ValidationIssue[];
  /** Overall confidence in the extraction (0–100). */
  confidence: number;
  /** Telemetry for logging and future analytics. */
  metadata: AgentResponseMetadata;
}

export interface AgentResponseMetadata {
  tokensUsed: number;
  latencyMs: number;
  model: string;
}

// ---------------------------------------------------------------------------
// Conversation context (fed into the LLM)
// ---------------------------------------------------------------------------

export interface ConversationContext {
  projectId: string;
  conversationId: string;
  /** The current requirement snapshot so the LLM knows what's already captured. */
  requirementSnapshot: Record<string, unknown>;
  /** The most recent N messages for context window management. */
  recentMessages: Message[];
  /** Rolling summary of older messages (generated by the summarization prompt). */
  conversationSummary?: string;
}

// ---------------------------------------------------------------------------
// LLM abstraction
// ---------------------------------------------------------------------------

export interface LLMCompletionOptions {
  model?: string;
  maxTokens?: number;
  temperature?: number;
  systemPrompt?: string;
  /** If true, the provider should return a ReadableStream. */
  stream?: boolean;
}

export interface LLMCompletionResult {
  content: string;
  tokensUsed: number;
  model: string;
}

export interface LLMStreamChunk {
  content: string;
  done: boolean;
}

/** Contract that every LLM provider must implement. */
export interface LLMProvider {
  complete(prompt: string, options?: LLMCompletionOptions): Promise<LLMCompletionResult>;
  streamComplete(prompt: string, options?: LLMCompletionOptions): AsyncIterable<LLMStreamChunk>;
}

// ---------------------------------------------------------------------------
// API payloads
// ---------------------------------------------------------------------------

export interface ChatRequest {
  projectId: string;
  conversationId: string;
  message: string;
}

export interface ChatResponse {
  agentResponse: AgentResponse;
  conversationId: string;
  messageId: string;
}

export interface RequirementUpdateRequest {
  field: RequirementFieldKey;
  value: unknown;
}
